# Generated by Django 6.1.1 on 2026-09-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_listing_price_at_listing_tamsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ai_predicted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI estimated price at the time of prediction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='reference_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Benchmark market price for the commodity/date', max_digits=10, null=True),
        ),
    ]
