# Generated by Django 6.1 on 2026-09-16 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_at_listing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TAMSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_usefulness', models.IntegerField(help_text='Rating from 1-5 on Perceived Usefulness')),
                ('perceived_ease_of_use', models.IntegerField(help_text='Rating from 1-5 on Perceived Ease of Use')),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tam_surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
